package com.bwton.vo.operatorManagement.query;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.yanyan.core.lang.PageQuery;
import com.yanyan.data.domain.system.Staff;
import com.yanyan.data.domain.system.vo.RoleVo;

import lombok.Data;
import lombok.extern.slf4j.Slf4j;


@Slf4j
@Data
public class OperatorInformationQuery  extends  PageQuery  implements  Serializable{
	
	private  String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_information.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_information.Operator_name
     *
     * @mbg.generated
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_information.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_information.operator_desc
     *
     * @mbg.generated
     */
    private String operatorDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_information.Service_state
     *
     * @mbg.generated
     */
    private String serviceState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_information.last_modify_user
     *
     * @mbg.generated
     */
    private String lastModifyUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_information.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;
    
   
}