package com.bwton.vo.contacts.query;

import java.io.Serializable;

import com.bwton.vo.operatorManagement.OperatorInformation;
import com.yanyan.core.lang.PageQuery;

import lombok.Data;

@Data
public class ContactsVoQuery extends  PageQuery  implements  Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.opIn_id
     *
     * @mbg.generated
     */
    private Integer opinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.telphone
     *
     * @mbg.generated
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.adress
     *
     * @mbg.generated
     */
    private String adress;

   
}