package com.bwton.persist.operatorManagement;


import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bwton.vo.operatorManagement.OperatorInformation;
import com.bwton.vo.operatorManagement.OperatorInformationExample;
import com.yanyan.core.lang.Page;

public interface OperatorInformationDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    long countByExample(OperatorInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int deleteByExample(OperatorInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int insert(OperatorInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int insertSelective(OperatorInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    Page<OperatorInformation> selectByExample(OperatorInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    OperatorInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperatorInformation record, @Param("example") OperatorInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperatorInformation record, @Param("example") OperatorInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperatorInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_operator_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperatorInformation record);
}