package com.bwton.vo.contacts;


import java.io.Serializable;

import lombok.Data;

@Data
public class ContactsVo    implements  Serializable {
	
	
	
	
	
	
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.opIn_id
     *
     * @mbg.generated
     */
    private Integer opinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.telphone
     *
     * @mbg.generated
     */
    private String telphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_operator_contacts.adress
     *
     * @mbg.generated
     */
    private String adress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_operator_contacts.id
     *
     * @return the value of g_operator_contacts.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_operator_contacts.id
     *
     * @param id the value for g_operator_contacts.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_operator_contacts.opIn_id
     *
     * @return the value of g_operator_contacts.opIn_id
     *
     * @mbg.generated
     */
    public Integer getOpinId() {
        return opinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_operator_contacts.opIn_id
     *
     * @param opinId the value for g_operator_contacts.opIn_id
     *
     * @mbg.generated
     */
    public void setOpinId(Integer opinId) {
        this.opinId = opinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_operator_contacts.name
     *
     * @return the value of g_operator_contacts.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_operator_contacts.name
     *
     * @param name the value for g_operator_contacts.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_operator_contacts.telphone
     *
     * @return the value of g_operator_contacts.telphone
     *
     * @mbg.generated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_operator_contacts.telphone
     *
     * @param telphone the value for g_operator_contacts.telphone
     *
     * @mbg.generated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_operator_contacts.email
     *
     * @return the value of g_operator_contacts.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_operator_contacts.email
     *
     * @param email the value for g_operator_contacts.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_operator_contacts.adress
     *
     * @return the value of g_operator_contacts.adress
     *
     * @mbg.generated
     */
    public String getAdress() {
        return adress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_operator_contacts.adress
     *
     * @param adress the value for g_operator_contacts.adress
     *
     * @mbg.generated
     */
    public void setAdress(String adress) {
        this.adress = adress == null ? null : adress.trim();
    }
}